export const SLIDE_ACTIVE_SCALE = 1.04;
export const SLIDE_ACTIVE_SCALE_MOBILE = 1.03;
export const SLIDE_SCROLL_DURATION_MS = 170;
export const SLIDE_CARD_TRANSFORM_DURATION_MS = 95;
export const SLIDE_TOUCH_THRESHOLD_PX = 1;
export const SLIDE_RESISTANCE_RATIO = 0.48;
